name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Backend
      run: mvn -f backend/pom.xml clean package -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/banking-backend ./backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/banking-frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/banking-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/banking-frontend
